import { useCallback, useEffect, useRef, useState } from 'react';
import { InlineError, Modal } from './components';
import { runtimeBridge, type RuntimeRun, type RuntimeSchedule, type RuntimeStatus, type RuntimeInterfaceSummary, type RuntimeScheduleSummary } from './runtime';
import { libraryError, LibraryValidationError } from './library-errors';
import { LibraryRequestFence, validateScheduleBounds } from './library-interactions';
import { listKeyboard, runtimeExecutionUnavailable, runtimeUnavailable } from './InterfacesView';

function utc(value?: string) { return value ? `${new Date(value).toISOString().replace('.000Z', ' UTC')}` : 'Not scheduled'; }

/** Execution fields change independently of the schedule's authorization/CAS version. */
export async function readScheduleSnapshot(workspaceId: string, selectedId: string | null, current: () => boolean, bridge = runtimeBridge) {
  const [schedules, interfaces, runs] = await Promise.all([bridge.listSchedules(workspaceId), bridge.listInterfaces(workspaceId), bridge.listRuns(workspaceId)]);
  if (!current()) return null;
  const selected = selectedId && schedules.some(schedule => schedule.id === selectedId) ? await bridge.getSchedule(selectedId) : null;
  return current() ? { schedules, interfaces, runs, selected } : null;
}

export function ScheduleControls({ selected, busy, unavailable, executionReason, onPause, onReview, onCopy }: { selected: RuntimeSchedule; busy: boolean; unavailable: string | null; executionReason: string | null; onPause: () => void; onReview: () => void; onCopy: () => void }) {
  return <div className="library-actions">{selected.state === 'enabled' ? <button type="button" className="button secondary" disabled={busy || !!unavailable} onClick={onPause}>{busy ? 'Pausing…' : 'Pause schedule'}</button> : <button type="button" className="button primary" disabled={busy || !!unavailable || !!executionReason || selected.state === 'ended' || Date.parse(selected.endAt) <= Date.now() || selected.runsStarted >= selected.maxRuns || selected.grantRefs.length > 0} onClick={onReview}>Review & enable</button>}<button type="button" className="button secondary" disabled={busy || !!unavailable} onClick={onCopy}>Create edited paused copy</button></div>;
}
export function SchedulesView({ active, native, status, workspaceId, modelId, onSettings }: { active: boolean; native: boolean; status: RuntimeStatus | null; workspaceId: string | null; modelId: string; onSettings: () => void }) {
  const [items, setItems] = useState<RuntimeScheduleSummary[]>([]); const [interfaces, setInterfaces] = useState<RuntimeInterfaceSummary[]>([]); const [runs, setRuns] = useState<RuntimeRun[]>([]);
  const [selected, setSelected] = useState<RuntimeSchedule | null>(null); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const [dialog, setDialog] = useState<'create' | 'enable' | null>(null); const [target, setTarget] = useState(''); const [prompt, setPrompt] = useState(''); const [cron, setCron] = useState('0 9 * * 1-5'); const [endAt, setEndAt] = useState(''); const [maxRuns, setMaxRuns] = useState('10'); const [duration, setDuration] = useState('120'); const [toolCalls, setToolCalls] = useState('8'); const [iterations, setIterations] = useState('6'); const [tokens, setTokens] = useState('2048'); const [consent, setConsent] = useState(false);
  const request = useRef(new LibraryRequestFence()); const operating = useRef(false); const selectedRef = useRef(selected); selectedRef.current = selected;
  const unavailable = runtimeUnavailable(native, status) || (!status?.capabilities?.features.schedules ? 'The runtime has not acknowledged durable schedules.' : !workspaceId ? 'Open a workspace to manage its schedules.' : null);
  const executorReason = runtimeExecutionUnavailable(native, status);
  const context = JSON.stringify([status?.generation, workspaceId, unavailable]); const contextRef = useRef(context); contextRef.current = context;
  useEffect(() => {
    request.current.issue(); operating.current = false; selectedRef.current = null;
    setItems([]); setInterfaces([]); setRuns([]); setSelected(null); setDialog(null); setConsent(false); setError(''); setNotice(''); setLoading(false); setBusy(false);
    return () => { request.current.issue(); };
  }, [context]);
  const load = useCallback(async () => {
    if (unavailable || !workspaceId || operating.current) return;
    const sequence = request.current.issue(); const current = () => request.current.current(sequence) && contextRef.current === context;
    setLoading(true); setError('');
    try {
      const snapshot = await readScheduleSnapshot(workspaceId, selectedRef.current?.id ?? null, current);
      if (!snapshot || !current()) return;
      setItems(snapshot.schedules); setInterfaces(snapshot.interfaces); setRuns(snapshot.runs); setSelected(snapshot.selected);
    }
    catch (failure) { if (current()) setError(libraryError(failure)); }
    finally { if (current()) setLoading(false); }
  }, [unavailable, workspaceId, context]);
  useEffect(() => { if (active) void load(); }, [active, load]);
  const act = async (action: (current: () => boolean) => Promise<void>) => {
    if (operating.current || unavailable) return;
    operating.current = true; const sequence = request.current.issue(); const current = () => request.current.current(sequence) && contextRef.current === context;
    setLoading(false); setBusy(true); setError(''); setNotice('');
    try { await action(current); }
    catch (failure) { if (current()) setError(`${libraryError(failure)} The previous acknowledged schedule state is retained. Reload before retrying a version conflict.`); }
    finally { if (current()) { operating.current = false; setBusy(false); } }
  };
  const accept = (schedule: RuntimeSchedule) => { setItems(previous => [schedule, ...previous.filter(s => s.id !== schedule.id)]); setSelected(schedule); };
  const title = (schedule: RuntimeScheduleSummary) => interfaces.find(i => i.id === schedule.interfaceId)?.title || `Interface ${schedule.interfaceId}`;
  const next = (schedule: RuntimeScheduleSummary) => schedule.state !== 'enabled' ? 'Not scheduled' : schedule.nextRunAt ? Date.parse(schedule.nextRunAt) < Date.now() ? `Overdue / executor status unknown · ${utc(schedule.nextRunAt)}` : utc(schedule.nextRunAt) : 'Unknown — no next fire returned';
  const create = () => void act(async current => {
    if (!workspaceId) return;
    const validation = validateScheduleBounds(cron, endAt, Number(maxRuns)); if (validation) throw new LibraryValidationError(validation);
    const budgets = { maxDurationSeconds: Number(duration), maxToolCalls: Number(toolCalls), maxIterations: Number(iterations), maxOutputTokens: Number(tokens) };
    for (const [key, value] of Object.entries(budgets)) { const ceiling = status?.capabilities?.limits[key as keyof typeof budgets]; if (!Number.isInteger(value) || value < (key === 'maxToolCalls' ? 0 : 1) || !ceiling || value > ceiling) throw new LibraryValidationError(`Budget ${key} must fit the acknowledged runtime limit.`); }
    const artifact = interfaces.find(item => item.id === target); if (!artifact || !modelId) throw new LibraryValidationError('Choose a saved target interface and an accepted Hermes model first.');
    const saved = await runtimeBridge.createSchedule({ workspaceId, interfaceId: artifact.id, expectedInterfaceRevision: artifact.revision, prompt: prompt.trim(), modelId, cron: cron.trim(), timezone: 'UTC', endAt, maxRuns: Number(maxRuns), budgets, grantRefs: [] });
    if (!current()) return;
    if (saved.state !== 'paused') throw new LibraryValidationError('Runtime returned an unexpected schedule state. Reload to reconcile; do not assume it is paused.');
    accept(saved); setDialog(null); setNotice('Saved paused. No execution is authorized until the separate Enable schedule review.');
  });
  const visible = items.filter(item => `${title(item)} ${item.id}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  const history = selected ? runs.filter(run => run.scheduleId === selected.id) : [];
  return <section className="library-page" hidden={!active} aria-labelledby="schedules-title" onKeyDown={listKeyboard}>
    <div className="library-heading"><div><span className="eyebrow">BOUNDED, OPERATOR-ENABLED</span><h1 id="schedules-title" tabIndex={-1}>Schedules</h1><p>Saved requests start paused. Every started attempt consumes a finite budget, including failures.</p></div><div className="library-actions"><button type="button" className="button secondary" disabled={loading || busy || !!unavailable} onClick={() => void load()}>{loading ? 'Refreshing…' : 'Reload status'}</button><button type="button" className="button primary" disabled={busy || !!unavailable} onClick={() => { setPrompt(''); setTarget(''); setEndAt(new Date(Date.now() + 7 * 86_400_000).toISOString().replace(/\.\d{3}Z$/, 'Z')); setDialog('create'); }}>New paused schedule</button></div></div>
    {unavailable && <div className="library-notice"><p>{unavailable}</p><button type="button" className="button secondary" onClick={onSettings}>Hermes status</button></div>}
    <div className="library-notice"><p><strong>Enabled is intent, not proof of running.</strong> Hermes is managed by Forma on this desktop. Execution device {status?.capabilities?.deviceId || 'not yet acknowledged'}. Check actual run history for outcomes.</p><p>Scheduled work requires Forma and this machine to remain running and awake, including when the window is hidden. Quitting Forma or powering off stops execution. Continuous operation is not verified here. Missed fires are skipped, not replayed in a burst.</p></div>
    {error && <InlineError onRetry={() => void load()}>{error}</InlineError>}{notice && <p role="status" className="field-note">{notice}</p>}{loading && <p role="status" className="field-note">Loading durable schedule records; previous state retained.</p>}
    <label className="library-search">Find a schedule<input data-library-search aria-label="Search schedules" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search target or schedule ID…" /></label>
    <div className="library-table-scroll"><table className="library-table"><thead><tr><th>Target / request</th><th>Status</th><th>Cron · UTC</th><th>Next run</th><th>Attempts left</th></tr></thead><tbody>{visible.map(schedule => <tr key={schedule.id}><td><button type="button" data-library-row className="library-row-button" disabled={busy} onClick={() => void act(async current => { const detail = await runtimeBridge.getSchedule(schedule.id); if (current()) setSelected(detail); })}>{title(schedule)}<span>Schedule {schedule.id}</span></button></td><td>{schedule.state === 'ended' ? 'Ended' : schedule.state === 'enabled' ? 'Enabled' : 'Paused'}{schedule.reason && <small className="row-detail">{schedule.reason}</small>}</td><td><code>{schedule.cron}</code></td><td>{next(schedule)}</td><td>{Math.max(0, schedule.maxRuns - schedule.runsStarted)} / {schedule.maxRuns}</td></tr>)}</tbody></table></div>
    {!visible.length && !loading && <div className="library-empty"><h2>{query ? 'No matching schedules' : 'No schedules yet'}</h2><p>{query ? 'Clear the search to return to your saved requests.' : 'Create a finite refresh request for a saved interface. Nothing runs by default.'}</p>{query && <button type="button" className="button secondary" onClick={() => setQuery('')}>Clear search</button>}</div>}
    {selected && <section className="schedule-detail"><div className="section-heading"><h2>{title(selected)}</h2><span className="status-chip">{selected.state} · version {selected.version}</span></div><p>{selected.prompt}</p><dl className="runtime-facts"><dt>Schedule ID</dt><dd>{selected.id}</dd><dt>Workspace</dt><dd>{selected.workspaceId}</dd><dt>Reason</dt><dd>{selected.reason || 'No additional reason returned'}</dd><dt>Next run (UTC)</dt><dd>{next(selected)}</dd><dt>Deadline (UTC)</dt><dd>{utc(selected.endAt)}</dd><dt>Attempts started</dt><dd>{selected.runsStarted} / {selected.maxRuns}; pausing/resuming never resets this counter</dd><dt>Per-attempt limits</dt><dd>{selected.budgets.maxDurationSeconds}s · {selected.budgets.maxIterations} iterations · {selected.budgets.maxToolCalls} tools · {selected.budgets.maxOutputTokens} output tokens/completion</dd><dt>Last run</dt><dd>{selected.lastRunId ? runs.find(run => run.id === selected.lastRunId)?.state || 'Outcome not in returned history — unknown' : 'Never run'}</dd><dt>Account grants</dt><dd>{selected.grantRefs.length ? `${selected.grantRefs.length} runtime-scoped references; live account use unavailable` : 'None — no account data'}</dd></dl>
      <ScheduleControls selected={selected} busy={busy} unavailable={unavailable} executionReason={executorReason} onPause={() => void act(async current => { const paused = await runtimeBridge.pauseSchedule(selected.id, selected.version); if (!current()) return; accept(paused); setNotice(paused.state === 'paused' ? 'Pause acknowledged. Future starts fenced; this is not rollback of already performed work.' : 'Runtime returned a different schedule state. Reload to reconcile; do not assume it is paused.'); })} onReview={() => { setConsent(false); setDialog('enable'); }} onCopy={() => { setTarget(selected.interfaceId); setPrompt(selected.prompt); setCron(selected.cron); setMaxRuns(String(Math.max(1, selected.maxRuns - selected.runsStarted))); setEndAt(new Date(Date.now() + 7 * 86_400_000).toISOString().replace(/\.\d{3}Z$/, 'Z')); setDialog('create'); }} />
      {executorReason && <p className="field-note">Enable unavailable: {executorReason}</p>}{selected.grantRefs.length > 0 && <p className="field-note">Enable unavailable: this client cannot review runtime grant scope/egress details. No inherited account approval.</p>}
      <p className="field-note">Editing creates a separate paused schedule; it does not replace or pause the original. No hidden retry loop and no overlapping attempts. Target revision is captured at each run start; stale publication is rejected.</p>
      <h3>Actual run history</h3><div className="run-history">{history.map(run => <details key={run.id}><summary>{run.state} · {utc(run.startedAt || run.createdAt)}</summary><dl className="runtime-facts"><dt>Run</dt><dd>{run.id}</dd><dt>Model</dt><dd>{run.modelId}</dd><dt>Reason</dt><dd>{run.reason || 'No additional reason returned'}</dd><dt>Finished</dt><dd>{run.finishedAt ? utc(run.finishedAt) : 'No terminal timestamp returned'}</dd></dl></details>)}</div>{!history.length && <p className="field-note">{selected.runsStarted ? 'No matching run records in the returned history page. Reload; do not infer success.' : 'Never run. No executions have started.'}</p>}
    </section>}
    {dialog && <Modal title={dialog === 'create' ? 'Create a paused schedule' : 'Enable this finite schedule?'} className="library-modal" onClose={() => setDialog(null)} dismissible={!busy}>
      {dialog === 'create' ? <form className="runtime-form" onSubmit={event => { event.preventDefault(); create(); }} onKeyDown={event => { if ((event.metaKey || event.ctrlKey) && event.key === 'Enter') { event.preventDefault(); event.currentTarget.requestSubmit(); } }}><fieldset disabled={busy}>
        <p className="field-note">Workspace {workspaceId} · accepted Hermes model {modelId || 'not selected — choose one in chat first'}. Hermes runs on this desktop. Saved paused, with no account grant.</p>
        <label>Target interface<select autoFocus value={target} required onChange={event => setTarget(event.target.value)}><option value="">Choose a saved interface</option>{interfaces.map(item => <option value={item.id} key={item.id}>{item.title} · r{item.revision}</option>)}</select></label>
        <label>Bounded read/refresh request<textarea value={prompt} required maxLength={16000} rows={3} onChange={event => setPrompt(event.target.value)} /></label>
        <label>Five-field cron · UTC<input value={cron} required maxLength={100} aria-describedby="cron-help" onChange={event => setCron(event.target.value)} /></label><p id="cron-help" className="field-note">Minute · hour · day-of-month · month · day-of-week. Numeric *, comma lists, ranges, positive steps. Day-of-month OR day-of-week when both restricted. The server validates the exact parser and eligible fire time; this UI never invents next times.</p>
        <label>Absolute end time · UTC<input value={endAt} required maxLength={32} placeholder="2026-09-17T18:00:00Z" onChange={event => setEndAt(event.target.value)} /></label>
        <div className="runtime-form-grid"><label>Maximum attempts<input type="number" min={1} max={100} step={1} required value={maxRuns} onChange={event => setMaxRuns(event.target.value)} /></label><label>Attempt timeout (seconds)<input type="number" min={1} max={status?.capabilities?.limits.maxDurationSeconds} step={1} required value={duration} onChange={event => setDuration(event.target.value)} /></label><label>Tool-call budget<input type="number" min={0} max={status?.capabilities?.limits.maxToolCalls} step={1} required value={toolCalls} onChange={event => setToolCalls(event.target.value)} /></label><label>Iteration budget<input type="number" min={1} max={status?.capabilities?.limits.maxIterations} step={1} required value={iterations} onChange={event => setIterations(event.target.value)} /></label><label>Output tokens per completion<input type="number" min={1} max={status?.capabilities?.limits.maxOutputTokens} step={1} required value={tokens} onChange={event => setTokens(event.target.value)} /></label></div>
        <p className="field-note">Google grants: unavailable, none selected. Live read/compliance/retention gates remain closed. This schedule can only operate on non-account content.</p>
      </fieldset><div className="modal-actions"><button type="button" className="button secondary" disabled={busy} onClick={() => setDialog(null)}>Cancel</button><button type="submit" className="button primary" disabled={busy || !target || !modelId || !prompt.trim()}>{busy ? 'Saving…' : 'Save paused'}</button></div></form> : selected && <><dl className="runtime-facts"><dt>Request</dt><dd>{selected.prompt}</dd><dt>Target</dt><dd>{title(selected)} · latest revision captured at run start</dd><dt>Cadence</dt><dd>{selected.cron} · UTC; next time returned only after acknowledged enable</dd><dt>Limits</dt><dd>{selected.maxRuns - selected.runsStarted} remaining attempts, ends {utc(selected.endAt)}, {selected.budgets.maxDurationSeconds}s/attempt, {selected.budgets.maxToolCalls} tools</dd><dt>Execution device</dt><dd>{status?.capabilities?.deviceId || 'Unknown'}</dd><dt>Hermes execution</dt><dd>Forma-managed on this desktop</dd><dt>Model destination / model</dt><dd>{status?.capabilities?.modelOrigin || 'Unknown'} · {selected.modelId}</dd><dt>Account data</dt><dd>None; no grants. Only the request, authorized conversation and non-account interface data may be processed.</dd><dt>Retention</dt><dd>Runtime stores run/audit/interface records; external model retention unknown. Already sent data cannot be recalled.</dd></dl><p className="field-note">Forma and this desktop must remain running and awake. Quitting Forma stops execution. Continuous liveness is not verified. Missed slots are skipped. Failures consume attempts. Pausing does not undo completed work.</p><label className="consent-check"><input type="checkbox" checked={consent} onChange={event => setConsent(event.target.checked)} /><span>I authorize this exact finite request, cadence, limits and runtime/model egress. This does not grant Google account access or consequential actions.</span></label><div className="modal-actions"><button type="button" className="button secondary" disabled={busy} onClick={() => setDialog(null)}>Keep paused</button><button type="button" className="button primary" disabled={busy || !consent || !!unavailable || !!executorReason || selected.state === 'ended' || Date.parse(selected.endAt) <= Date.now() || selected.runsStarted >= selected.maxRuns || selected.grantRefs.length > 0} onClick={() => void act(async current => { if (executorReason) return; const enabled = await runtimeBridge.enableSchedule(selected.id, selected.version, { scheduleVersion: selected.version, modelId: selected.modelId, grantRefs: selected.grantRefs }); if (!current()) return; accept(enabled); setDialog(null); setNotice('Enable acknowledged by the runtime. Check actual run history; this is not proof of executor liveness.'); })}>{busy ? 'Enabling…' : 'Enable schedule'}</button></div></>}
      {error && <InlineError>{error}</InlineError>}
    </Modal>}
  </section>;
}
